# Your CI system must already have apex installed. www.apex.run

variables:
    AWS_REGION: "us-east-1"
    # AWS Username and Password are not stored in the .gitlab-ci.yml. They are stored securly in the project pipeline settings.

deploy:
    stage: deploy
    image: python:latest
    script:
        - npm install
        - npm run build
        - npm test
        - apex deploy
